### ISSUE TITLE
Save message as...

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#100]
As a user, I want to be able to provide the file name when I select the directory in which to save the message.

**Tasks**

- [x] Above select folder list, provide field for File Name
- [x] Add "Save" button
- [x] Upon save, create new file in destination folder using the provided name
- [x] Display notification of save result
- [x] Test
