### ISSUE TITLE
Finalize "Save Message As" Feature

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#101]
As a developer, I would like the updated UI design for the Save As feature to be optimized from a code perspective.

**Tasks**

- [x] Add functionality for "Open file after saving"
- [x] Select proposed name in filename field when opening the Save As modal
- [x] Add default messages folder in plugin settings
- [x] Display notification if file already exists, and leave modal open
- [x] Improve error user notification
- [x] Test
