### ISSUE TITLE
Stop auto-scrolling if the user manually scrolls

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#104]
As a user, I want to stop auto-scrolling during a streaming response so I can read where I'm at without it moving off the screen.

**Tasks**

- [x] Detect when user scrolls
- [x] Interrupt auto-scroll
- [x] Ensure that keyboard navigation still works as expected
- [x] Test
