### ISSUE TITLE
Disable send during streaming response to view

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#127]
As a user, I don't want to inadvertently send a request when the previous one hasn't yet completed. This will prevent requests from being interrupted or split.

**Tasks**

- [x] View: Disable send when message is sent
- [x] View: Add disabled class (or different icon?) for visual indication
- [x] View: Enable send upon stream end
