### ISSUE TITLE
FIX: Prompt Modal can send while response is in progress

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#129]
As a user, if I'm using a modal to send a prompt, if the specific target (e.g. tab or view) is receiving a response, I would like Send to be disabled.

**Tasks**

- [ ] Identify target
- [ ] Provide modal with target
- [ ] Prevent send if target is currently receiving a response
- [ ] Elements style should reflect the disabled-state just as with the view message pad
- [ ] Test
