### ISSUE TITLE
During streaming response to editor, suppress keystrokes

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#130]
As a user, I don't want the streaming response to a note to be interrupted or broken by typing any characters. I would still like to use the escape key to stop the response though.

**Tasks**

- [x] Detect keystrokes
- [x] Make exception for esc key
- [x] Prevent default behavior until response is complete
- [x] Escape key should still cancel the streaming response to the target note
- [x] Test
