### ISSUE TITLE
Send Selected Text as Prompt with Instructions via Modal

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#14]
As a user, I want to be able to highlight text in a note, send it along with a custom prompt to the GPT API, and see the response, to test the basic functionality of text interaction with GPT.

## Tasks:
  - [x] Add a command that appears only when text is selected. This command should be named something like "Send selected text with instructions"
  - [x] When command is selected, open a modal dialog box to allow the user to enter a custom prompt to send to the GPT API.
  - [x] Construct and make the API payload combining the user's selected text with their entered prompt.
  - [x] Display the API's response in the plugin's right-side view
