### ISSUE TITLE
Refactor ApiService to Enhance Modularity and Maintainability

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#27]
**As a developer**, I want to refactor `apiService.ts` to separate the method handling and API calling logic into different files, enhancing the modularity and maintainability of our codebase.

**Tasks:**
- [x] Identify and isolate methods such as `getEngines` and similar functions into a new file, tentatively named `features.ts`.
- [x] Test all features for previous functionality.
- [x] Define a set of properties that describe the "feature" to be referenced by the methods in `features.ts` and send to the API request.
- [x] Update `apiService.ts` to receive and process the appropriate properties.
