### ISSUE TITLE
Improve Chat View Clarity by Hiding Selected Text

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#46]
As a note editor, I want to hide the selected text in the chat view to reduce visual noise.

**Tasks:**

- [x] Refactor prompt building to separate user prompt and selected text
- [x] (a) Display only the prompt in the chat view, OR
      (b) Display selected text in distinct style
- [x] (Optional) Add selected text as a property
- [x] Test changes to ensure functionality and clarity improvements
