### ISSUE TITLE
Refactor to use OpenAI Chat Completions API

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#53]
As a developer, I want to use the OpenAI Chat Completions API instead of doing a manual API request, so that the responses are more robust and OpenAI features may be used going forward.

**Tasks**

- [x] Refactor ApiService to use OpenAI Chat Completions API for streaming requests
- [x] Refactor ApiService to use OpenAI Chat Completions API for non-streaming requests
- [x] Update dependent interfaces, etc. to comply
- [x] Update GptFeatures to align with ApiService
