### ISSUE TITLE
Codebase Clean-up and Streamlining

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#54]
As a developer, I would like to clean up and streamline the codebase to improve maintainability and readability so that future development is more efficient and less error-prone. This is also in preparation for improved message handling.

**Tasks**

- [x] Refactor components and utilities into a more organized directory structure, specifically moving files like `Message.tsx` and `Messages.tsx` into the `src/components` directory.
- [x] Optimize imports and dependencies by removing unused modules and consolidating imports to improve module management and load times.
- [x] Test for maintained functionality
