### ISSUE TITLE
Real-time scrolling during streaming response

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#59]
As a user, I want to scroll through content within the GPT chat view to navigate long conversations and access previous messages easily.

**Tasks:**

- [ ] Investigate the possibility of real-time scrolling that synchronizes with streaming new messages to keep users updated without manual scrolling.
- [ ] Add hotkey [p] pause/unpause scroll
- [ ] Test these navigation features to ensure they are intuitive and enhance the user experience across different devices and screen sizes.
