### ISSUE TITLE
Prompt text box in chat view

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#73]
As a user, I would like a persistent text box in the chat view so that 

**Tasks**

- [x] Same behavior as current modal, i.e. cmd-return to submit prompt
- [x] "Send" button or icon
- [x] Add hotkey to focus text box
- [x] Test to ensure layout, scrolling, and message navigation remains functional
