### ISSUE TITLE
Save chat thread to note

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#74]
As a user, I want to save an entire chat thread to a note so I have record of it for reference and use.

**Tasks**

- [x] Save when "New Chat" is clicked
- [x] Location of file
    - [x] Default location (add to settings panel?)
    - [x] Ad hoc user-specified location (use Obsidian selector for this)
- [x] New file created
- [x] Content of chat copied to new note
- [x] Note saved to default or specified location
- [x] Opt-click on New Chat doesn't save to file. Just clears chat.
- [x] Test
