### ISSUE TITLE
Highlight messages as they are scrolled to using the hotkeys

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#81]
As a user, I would like to know which message in the chat view has the "focus" so that I know when I use the next or previous hotkeys where in the stream it's going to go next.

**Tasks**

- [x] Determine way of indicating the focused message
- [x] Create CSS to style the design
- [x] Add or update JS to provide the functionality
- [x] Test
