### ISSUE TITLE
Display model used under prompt input

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#83]
As a user, I would like to see the model being used when I input my prompt. This is helpful when using features that use a specific model.

**Tasks**

- [x] Design location and style of model text in the prompt UI
- [x] Display model specified by user in settings
- [x] Else display model from plugin default settings 
- [x] Test in chat view and in various modals
