### ISSUE TITLE
Refactor `notifyError` as `notify`

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#92]
As a Quill developer, I would like to refactor `notifyError` as `notify`, so that it can be used a a general utility for displaying Obsidian alerts, whether or not they are error-related.

**Tasks**

- [ ] Rename method
- [ ] Change args to accommodate new functionality
    - [ ] Make `errorCode` optional
    - [ ] Add optional(?) `messageCode`
- [ ] Update method calls
- [ ] Test
