### ISSUE TITLE
Add "Save message to note" action

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#93]
As a user, I want to instantly save a message in the view to a new note.

**Tasks**

- [x] Add mechanism to save message
- [x] Add icon
- [x] Copy message content to note
- [x] Display notice that file is saved
- [x] Test
