### ISSUE TITLE
Add "copy message to clipboard" action

### ISSUE THREAD

**Issue by cathoderaynoob** [cathoderaynoob/obsidian-quill#96]
As a user, I would like a button to copy a Assistant message to the clipboard, so that I don't have to select the text manually.

**Tasks**

- [ ] Add button/icon to message
- [ ] Create method to copy message to clipboard
- [ ] Notify user that message has been copied
- [ ] Test
